### PR TITLE
made conversion to epoch time operations platform independent

### PR DESCRIPTION
**Pull request by NdibeRaymond**
**Issue involved** : #133 
It appears that strftime("%s") was used to convert datetime to epoch time but this is only supported in linux.
**What was changed**
 * Replaced strftime("%s") with timestamp() which is supported by both windows and Linux running 
 python 3.3 and above.
 * Added a fallback check that checks for Python version and then decides what method to use for the conversion.

**Why the check**
The version check is necessary because most servers run Python 2 which doesn't support timestamp().
So if Python 2 is being used, we default to strftime but if it's Python 3.3 and above, we use the more platform independent timestamp().

**Why is this fix necessary**
Most newbies use Windows for development. Without this fix, no newbie running Windows Will be able to contribute to the back-end of this project.

### CODE REVIEW

**Comment by muskangupta-iitr** [comment]
@NdibeRaymond You can reduce the redundancy of the PR. Like, you can create a function which returns the correct supported time stamp.
For example:
```
def return_OS_supported_date(input):
        if(version >= version_3_3):
             return input.timestamp())
        else:
             return = input.strftime("%s")
```
Any views?

**Comment by NdibeRaymond** [comment]
That's actually something I should have done. Thanks for pointing it out @muskangupta-iitr

**Comment by NdibeRaymond** [comment]
@srish, there is something I need clarification on. I saw a place where (t1 - beginning _of_internet_time).total_seconds() was used in result app view.py file and I wanted to know if there was any special reason this was being used instead of strftime("%s") because both appears to be doing same thing. I had a minor bug in this PR that made phab commits details not to show in Windows hosting environment (had something to do with daylight saving time). Though the minor bug has been fixed (will be pushing the changes to this PR before any merge), I wanted to know if there is any special reason total_seconds() was used instead of strftime("%s"). Maybe @rammanoj can help here

**Comment by srish** [comment]
@NdibeRaymond Yes, this is something @rammanoj might be able to answer! Reach out to him on Zulip. And, then let me know if/when I should merge this. I'm also wondering some of the crucial bugs we have around timing; for example, https://github.com/wikimedia/WikiContrib/issues/21 is also related, but I don't know.

**Comment by NdibeRaymond** [comment]
> @NdibeRaymond Yes, this is something @rammanoj might be able to answer! Reach out to him on Zulip. And, then let me know if/when I should merge this. I'm also wondering some of the crucial bugs we have around timing; for example, #21 is also related, but I don't know.

I'm almost done. Just needed to test it on a live Linux server as well just to be sure. And yes, I have a feeling this is definitely related to #21

**Comment by NdibeRaymond** [comment]
this is ready to be merged now @srish . was trying to fix a windows only problem with offset aware and offset naive datetime objects. has been fixed now

**Pull request merged**
