### PR TITLE
Remove hovering effect from cards that loading

### PR DESCRIPTION
**Pull request by ShcherbaDev**
Fix for #74 
I removed hovering effects for cards that are loading.

### CODE REVIEW

**Comment by rammanoj** [comment]
Tha ja for the patch. I am busy with some work... I will review and merge the task in next few hours. Sorry for the delay and thanks for the patch :)

**Comment by ShcherbaDev** [comment]
Ok, thanks

**Comment by srish** [comment]
@ShcherbaDev thanks a lot for your code contribution! Good luck working on other Google Code-in tasks :)

**Comment by ShcherbaDev** [comment]
@srsh thank you for response! My username in Google Code-in is "Crutishnyk".

**Comment by srish** [comment]
@ShcherbaDev Great! I just approved your task :)

**Pull request merged**
