### PR TITLE
Checked if usernames are valid or linked to the same person

### PR DESCRIPTION
**Pull request by NdibeRaymond**
*issue solve: #23*
show_mismatched
show_mismatched_detail

### CODE REVIEW

**Comment by NdibeRaymond** [comment]
@srish and @rammanoj , i submitted a fix for issue #23, please review

**Comment by NdibeRaymond** [comment]
@rammanoj and @srish, can you review and give your feedback on this PR?

**Comment by rammanoj** [comment]
@NdibeRaymond The change you made are good. But if my gerrit and phabricator name is completely different. Does it still work ?

**Comment by NdibeRaymond** [comment]
If the two names are completely different, it throws a prompt to warn you and ask you if you want to continue. A simple change can make it reject entirely but I thought that maybe someone might want to use this to compare different users graphs. In that case, it still shows but it will warn you about what you are doing. For the example you gave, it doesn't compare the username with the fullname. It uses the username you gave to fetch the users fullname from the appropriate platform, then compare the fetched fullname to the provided fullname. The assumption is that the user used their true fullname while registering the account. This is yet another reason why I allowed it to show even when the fullnames doesn't match, because I found out that some users used a completely unrelated full name to register their accounts (like submitted fullname:"Ndibe Raymond", phab_fullname: "Olisaemeka__UNR"). In this case, it's actually the same user just that the fullnames are unrelated, so the app warns you that the fullnames are unrelated and If you want to continue. If the person making the query is the account owner, they wouldn't like the prompt so will be forced to go back later and edit their accounts fullname, this way, the functionality doesn't create any unpleasant obstruction and yet still succeeds in alerting users for mismatched usernames

**Comment by rammanoj** [comment]
Thanks @NdibeRaymond  for the explanation. Working fine locally :)

**Pull request merged**
