### PR TITLE
changed tool urls to reflect the changes made to toolforge root url

### PR DESCRIPTION
**Pull request by NdibeRaymond**
Toolforge's root url was recently changed to start using a subdomain format. This PR modified wikicontrib tool to reflect this change as it broke the application.

### CODE REVIEW

**Comment by srish** [comment]
@NdibeRaymond Thanks for making the changes! Looks good to me. Perhaps, we should make the necessary change in `.env.example` as well?

**Comment by NdibeRaymond** [comment]
> @NdibeRaymond Thanks for making the changes! Looks good to me. Perhaps, we should make the necessary change in `.env.example` as well?

Yeaa, not just that. Sorry I didn't look closer. Found out there are more corrections to make. Will push the changes soon

**Comment by rammanoj** [comment]
Everything looks good to me @srish Let's merge and see if it goes fine.

**Comment by rammanoj** [comment]
If this happens, it is really critical bug. Let's undo the commit made by her.

**Pull request merged**
