### PR TITLE
Fixed #131

### LINKED ISSUE #131: Fix overflow of blocks in total contributions card
The monthly contributions blocks are overflowing the total contributions card from both sides. 
They need to be contained inside the card. One way to do this would be adding a scrollable feature to their outer div. 

image

### PR DESCRIPTION
**Pull request by shivanigangadharan**
@srish The blocks overflowed when the screen width was above 1456px. So I created a media query for the same and it looks good on laptop view now. Auto-resizing is yet to be done though, still trying to figure that out. Hope this much works well, let me know how it looks on your screen, thanks!

### CODE REVIEW

**Comment by rammanoj** [comment]
Please check [this](https://github.com/wikimedia/WikiContrib/issues/131#issuecomment-605609866)

**Comment by shivanigangadharan** [comment]
> Hi! I just tested your changes. For resolution with width < 600 px, I still see the overflow issue in laptop view: 
> Could you take a re-look?

I just checked, yes on resizing it does overflow but as @rammanoj mentioned, I think we need to refresh it in order to view the correct dimensions. Also as you mentioned, I tried the screen for a width<600px. In the picture below, I have kept the width as 420px, then it looks good after refreshing. Let me know if the problem still persists, thanks. 

image

**Comment by srish** [comment]
Thanks, @shivanigangadharan, for these changes. About the overflow issue in general, I still think that the blocks should re-adjust without having to do the refresh on the screen. But, your changes to fix the overflow on screens > 1456px is a helpful step.

**Comment by shivanigangadharan** [comment]
> Thanks, @shivanigangadharan, for these changes. About the overflow issue in general, I still think that the blocks should re-adjust without having to do the refresh on the screen. But, your changes to fix the overflow on screens > 1456px is a helpful step.

Right, I agree with that too. Will update when I arrive at a solution for that too, till then thanks a lot for all your guidance and help. It was great to work on this issue! :)

**Pull request merged**
