### PR TITLE
[WIP] Auto scroll to display activity when tile is clicked

### PR DESCRIPTION
**Pull request by eeshadutta**
I have modified the CSS in some places (Issue #147 )- 

1. Added a Navbar to the tool 

2. Changed the design of the page which displays the contributions - aligned the elements, changed the appearance of 'Query Result'. 
**Earlier**
Screenshot from 2020-03-19 19-29-59

**Now**
Screenshot from 2020-03-19 19-27-51

3. Modified the Activity section 
Screenshot from 2020-03-19 19-10-53

### CODE REVIEW

**Comment by srish** [comment]
@eeshadutta Hey! thanks for working on this. 

So, first, I have a comment – I tested your changes locally, and unfortunately, I like our previous design better than the one with your changes. Everything appears too big now, and the navbar feels not necessary. In one place, I have also noticed that the text is overlapping with an HTML element: 

Screen Shot 2020-03-20 at 9 23 15 PM

Another problem with this PR is that there are multiple font size changes that were not discussed. Generally, it is a good practice that after you file an issue, you wait for someone to give you feedback so that you don't end up spending time in something that might not be used later. 

Looking at the issue you filed, I think that the problem you have raised there is concrete and valid: "When a day with no contributions is clicked... one needs to scroll down to be able to see this message". It would be helpful that you can focus just on that for now and make any necessary changes to this PR and submit again for review. Also, I can see that you did something with the activity boxes, probably increased their width. So, you can file a separate issue around that first. Let me comment on it, and then you can send a separate PR for that. What do you think?

**Comment by eeshadutta** [comment]
@srish to clarify -
1) I should change the issue title and description on #147 to just account for: "When a day with no contributions is clicked... one needs to scroll down to be able to see this message". And I should make a PR for that?
2) Make an issue about changing the activity boxes. And after I receive feedback on that, I can work on that.
3) Remove the navbar and stick to the original design.  Should I change the font of 'Query Result' or let it be as it is?

Am I right?

**Comment by srish** [comment]
> @srish Thanks for the feedback! Just to clarify -
> 
> 1. I should change the issue title and description on #147 to just account for: "When a day with no contributions is clicked... one needs to scroll down to be able to see this message". And I should modify this PR accordingly?

Yes! The title can be short, you can rephrase. 
> 2. File a new issue about changing the activity boxes. And after I receive feedback on that, I can work on that.

Exactly. 
> 3. Remove the navbar and stick to the original design.  Should I change the font of 'Query Result' or let it be as it is? And should I align the search bar or leave it as it is?

Yeah, all these changes were problematic, so you can remove them all.

**Comment by eeshadutta** [comment]
@srish I will make the necessary changes

**Pull request closed without merging**
