### PR TITLE
Added 'go to top' functionality

### PR DESCRIPTION
**Pull request by NdibeRaymond**
This is an improvement over @harshika18 's PR. I removed the unnecessary setInterval delay, generally reduced the line of code and added @rammanoj 's icon recommendation

**issue fixed**: #180

go_to_top

### CODE REVIEW

**Comment by rammanoj** [comment]
@NdibeRaymond I think whenever you press the button it need to go to the top slowly (i.e introduce some delay).
Can you also check if the color of the button matches with view filters/update button color ? you are also welcomed to change the styles of button :)

**Comment by NdibeRaymond** [comment]
> @NdibeRaymond I think whenever you press the button it need to go to the top slowly (i.e introduce some delay).
> Can you also check if the color of the button matches with view filters/update button color ? you are also welcomed to change the styles of button :)

I actually think a slow go-to-top button is actually annoying and bad UX. when users want to go to the top, they want it to be fast. I personally hate it too and probably won't use it if it is slow. But then, if you think i should change it, I will make the necessary changes then update the PR

**Comment by NdibeRaymond** [comment]
I made the changes you requested @rammanoj. Review when you have time

**Comment by rammanoj** [comment]
+1 good to go. Thanks @NdibeRaymond and @harshika18 for working on the feature

**Pull request merged**
