### PR TITLE
Add a feature to go to the top directly

### PR DESCRIPTION
**Pull request by harshika18**
fixed [#180](https://github.com/wikimedia/WikiContrib/issues/180)

### CODE REVIEW

**Comment by rammanoj** [comment]
Cool feature @harshika18 :)
The code even looks good to me. But need to examine it correctly once. I will test it once locally and get back to you by tomorrow :)

**Comment by rammanoj** [comment]
@harshika18 A small suggestion, please try putting an arrow mark. Something like:
image
You can use arrow instead of "Top". It will be better I guess. You can add this code instead of "Top": 
```
<Icon name="caret up" size="big" inverted />
```
and also don't forget to import icon from 'semantic-ui-react'. Once you put the icon, please format it properly and add the commit to PR :)
Thanks for the PR

**Comment by NdibeRaymond** [comment]
@rammanoj , this PR looked abandoned as is the issue that led to this PR. Maybe we should close it and create a new PR with 
 improvements based on your suggestions in the comment above

**Comment by srish** [comment]
(hmm.. bad :-/ we have no option other than to close this PR for now and keep the issue still open)

**Pull request closed without merging**
