### PR TITLE
No focus outline for user input fields

### LINKED ISSUE #73: Remove outlines on focusing the inputs
> Note: This task is reserved for Google Code-in students. Please do not claim this task.

Upon focusing the inputs, there are blue borders being appeared.
image

This is not the fault of the tool, as far as I know, it is nature of the web browser. I can reproduce this in chrome and brave. But I could not see it in firefox. 

I haven't tested it with safari (But I guess safari also show the borders).

The border appears weird with the current UI and it does not appear in all the browsers. So, I guess  removing them will be better option...

For reference: https://medium.com/@ricardozea/how-to-remove-the-blue-border-outline-in-chrome-safari-and-dotted-line-in-firefox-edge-fe5e2155d44c

### PR DESCRIPTION
**Pull request by minhducsun2002**
Resolve #73.
(As soon as #93 gets merged, I'll claim the respective task in GCI.)

### CODE REVIEW

**Comment by srish** [comment]
@minhducsun2002 Thanks a lot for your code contribution! I tested your change on Chrome and Firefox and it works well there. You would need something more for Safari, you will probably get some hint here: https://stackoverflow.com/a/11475899.

**Comment by minhducsun2002** [comment]
> I would encourage you to not repeat the same in the future. 
Oh, sorry. I'll pay more attention to that.

Also, it seems like I cannot claim the task mentioned in #73. Is there any error?

**Comment by srish** [comment]
@minhducsun2002 It is because another candidate has claimed that task. So, that is the reason why I would encourage you not to start working on a task before your previous one is complete. You won't be able to claim a new one before your previous one has been approved, and we won't be able to reserve a task for you.

**Comment by rammanoj** [comment]
Closing the task, as the other one got merged.

**Pull request closed without merging**
