### PR TITLE
[un-mergeable] Response time research

### PR DESCRIPTION
**Pull request by NdibeRaymond**
**This PR is the result of the research done about #58 and #110**
**This research is divided into two:**
 * Asyncio based solution
 * Bitergia dev tool console based solution

to read about the second part, skip to the bottom

**Asyncio Based Solution**
**What it addresses**
 * Finding out how long it takes to fetch the contributions of a single user on average
 * Finding out how long it takes to fetch the contributions of a list of users

**HOW TO TEST**
 * clone my copy of this repo
 * Go to backend folder and enable your virtual env
 * Do the required setup
 * Switch to response_time_research branch
 * Start server for backend and front-end and try uploading a csv with the desired number 
   of usernames
If it doesn't redirect immediately, open your network tab and copy the hash in the last URL visited, then open a new tab and visit (localhost:3000/exp/hash)

 
list_view

**My Findings**
It seems like there is a cost associated with every additional user data retrieval. By that, I mean that the relationship between the number of users and the time taken to fetch their data is exponential. This is because of phabricator API rate limits. 
From my findings, the real problem are the two Phabricator endpoints. Gerrit always returns a response in like two seconds tops even when you are fetching like 20 users data.

**Proposed solution**
It will be very beneficial if we build a caching mechanism to limit the network hit to the phab API endpoints. You can go to issue #110  to read about how I think this can be done

**Bitergia Dev Tool Console Based Solution**

@rammanoj proposed another possible way of solving this issue by scraping bitergia dev tool console and provided the starter snippet for achieving this.
I have modified this research PR to include the research work I did based on his recommendation.

**What I did**
 * improved on his snippet to read queries from json, post the queries to bitergia dev tool console, 
  retrieve the result and store it in another json file

**HOW TO TEST**
 * clone my copy of this repo
 * Go to backend folder and enable your virtual env
 * Do the required setup (most importantly by running pip install -r requirements.txt)
 * Switch to response_time_research branch
 * Download chromedriver for your system and paste the executable inside bitergia_scraping folder 
  in the backend path of the project
 * Inside the bitergia_folder, open console and run "python bitergia_scraping_script.py"

Note that you will need to install openssl on your system (if you are not running windows) for this to work, since the seleniumwire package needed for this implementation requires it.

**Findings**
Minus the time it takes to properly startup chrome driver (this varies depending on system power), the query latency seems to be very short.
If we decide to take this method though, we might have to change the implementation if bitergia ever decides to tweak their code since this is not the approved way.
I also found that the results returned from the queries are paginated to ten items by default though I couldn't see any URL to go to prev and next pagination.

**Challenges to overcome before this can become viable**
 * Find a proper documentation detailing how to make proper queries on bitergia dev tool console.
 * Find a solution to the pagination problem as that can significantly increase the query latency.

**Please Note That This is work in progress as I will continue making changes based on future research findings. Anybody is free to contribute to this as well**
@srish @rammanoj

### CODE REVIEW

**Comment by QEDK** [comment]
You might want to squash these commits and force-push to the fork.

**Comment by NdibeRaymond** [comment]
> You might want to squash these commits and force-push to the fork.

OOOh thanks for the suggestion @QEDK , i think I should probably do that

**Comment by NdibeRaymond** [comment]
> This is really useful research! Thanks for working on this. It is good that we now have the approaches documented so that we can build upon them in the future.
> I've been trying to test this PR and I get the following error after uploading the CSV in a format that I shared here [#110 (comment)](https://github.com/wikimedia/WikiContrib/issues/110#issuecomment-597432397):
> 
> ```
> result.js:237 Uncaught TypeError: Cannot read property 'forEach' of undefined
>     at QueryResult.getGraphData (result.js:237)
>     at QueryResult.render (result.js:715)
>     at finishClassComponent (react-dom.development.js:17160)
>     at updateClassComponent (react-dom.development.js:17110)
>     at beginWork (react-dom.development.js:18620)
>     at HTMLUnknownElement.callCallback (react-dom.development.js:188)
>     at Object.invokeGuardedCallbackDev (react-dom.development.js:237)
>     at invokeGuardedCallback (react-dom.development.js:292)
>     at beginWork$1 (react-dom.development.js:23203)
>     at performUnitOfWork (react-dom.development.js:22157)
>     at workLoopSync (react-dom.development.js:22130)
>     at performSyncWorkOnRoot (react-dom.development.js:21756)
>     at react-dom.development.js:11089
>     at unstable_runWithPriority (scheduler.development.js:653)
>     at runWithPriority$1 (react-dom.development.js:11039)
>     at flushSyncCallbackQueueImpl (react-dom.development.js:11084)
>     at flushSyncCallbackQueue (react-dom.development.js:11072)
>     at scheduleUpdateOnFiber (react-dom.development.js:21199)
>     at Object.enqueueSetState (react-dom.development.js:12639)
>     at Query.push../node_modules/react/cjs/react.development.js.Component.setState (react.development.js:471)
>     at Query.callback (query.js:400)
>     at extractChunk (fetchFile.js:48)
>     at fetchFile.js:78
> ```
> 
> Do you have an idea why that might be happening? (I don't want to debug right now, if you maybe encountered a similar error, I can leverage your help ;-))
> 
> Also, I've one suggestion for documenting these results. Could you maybe move all the documentation you have done in the task description and issue 110 in a `RESEARCH.md` in the root folder? And, then also in that documentation, provide a link to this PR. Some of the unexplored territories related to Bitergia can be documented in the .md file as TODOS for future work. If/when you are ready to send a PR around the documentation, please do so, and then we can merge that one close this one.

Ok @srish , i will organize it properly then send a PR. Let we look into the error you shared above. i have an idea where it might be coming from

**Comment by NdibeRaymond** [comment]
@srish, the error has been resolved. should work ok now

**Comment by rammanoj** [comment]
:clap: Thanks for the research @NdibeRaymond Can I know if the biterg tool solution working fine ? If so can you please post the results. 
If you need to know more about sparql queries and elastic search. You can find more about the queries here: https://www.elastic.co/guide/en/elasticsearch/reference/current/elasticsearch-intro.html
If your research about biterg is complete, Can I know the amount of time it is taking to perform a api request ? Can you also compare it with different users ?

**Comment by NdibeRaymond** [comment]
@rammanoj , I can't give a specific value, since there are factors that vary from location to location and from local environment to local environment, such as internet speed and system power. What I did is implement it and create this PR, so anybody can clone it, setup the environment, change the value in the query JSON and run the script to observe how long it takes

**Comment by QEDK** [comment]
> @rammanoj , I can't give a specific value, since there are factors that vary from location to location and from local environment to local environment, such as internet speed and system power. What I did was implement it and create this PR, so anybody can clone it, setup the environment, change the value in query.json and run the script to observe how long it takes

I don't think local environment should have much impact given that queries are between WMCS infrastructure. Querying and benchmarking Elasticsearch inside Toolforge should do the trick.

**Comment by NdibeRaymond** [comment]
@QEDK , chromedriver actually takes sometime to start up, and this varies from system to system. Second, bitergia dev tool console also takes some time to load, and I think I am right to assume this is dependent on network speed. We can't be measuring query request response latency alone, since the above mentioned delays takes considerable amount of time. We can just subtract the chromedriver start up time and bitergia loading time from the total latency. And since these two varies considerably from system to system and network to network, assuming that the total latency on your system will be the same as that on another's system and the same when hosted on a server is simply wrong

**Comment by QEDK** [comment]
Ah yeah that's probably true, I am not familiar with other sources of
latency that are related to this.
To clarify, I'm talking about the Dev Tools response only - which is
received from the Elasticsearch instance, which can be benchmarked within
Toolforge separately if needed before being tacked on, before taking local
system considerations (such as Chromedriver). That's all. :)

**Comment by srish** [comment]
@NdibeRaymond feel free to close this too!

**Pull request closed without merging**
