### PR TITLE
Removed outline from user search input

### LINKED ISSUE #73: Remove outlines on focusing the inputs
> Note: This task is reserved for Google Code-in students. Please do not claim this task.

Upon focusing the inputs, there are blue borders being appeared.
image

This is not the fault of the tool, as far as I know, it is nature of the web browser. I can reproduce this in chrome and brave. But I could not see it in firefox. 

I haven't tested it with safari (But I guess safari also show the borders).

The border appears weird with the current UI and it does not appear in all the browsers. So, I guess  removing them will be better option...

For reference: https://medium.com/@ricardozea/how-to-remove-the-blue-border-outline-in-chrome-safari-and-dotted-line-in-firefox-edge-fe5e2155d44c

### PR DESCRIPTION
**Pull request by n3rsti**
Resolve #73 
I added outline prefix for other browsers.

### CODE REVIEW

**Comment by n3rsti** [comment]
I looked on CanIUse website and i don't need outline prefixes.

**Comment by srish** [comment]
@n3rsti Thanks a lot for your code contribution! I tested your change on Chrome and Firefox and it works well there. You would need something more for Safari, you will probably get some hint here: https://stackoverflow.com/a/11475899.

**Comment by n3rsti** [comment]
It should work now for Safari as well.

**Comment by rammanoj** [comment]
Cool @n3rsti, @srish can you check if it is working fine in safari ?

**Comment by n3rsti** [comment]
I don't have any macOS device. I tried on browserstack, but it haven't loaded.

**Comment by srish** [comment]
@n3rsti @rammanoj It is working fine folks! :) I'm merging the PR, thank you!!!

**Comment by srish** [comment]
@n3rsti you will have to sent back the task on the GCI site for review so that I can approve it.. ping me when you are done..

**Comment by n3rsti** [comment]
Thanks, I've sent back the task.

**Pull request merged**
