### PR TITLE
Fix timeframe calculation

### LINKED ISSUE #98: Incorrect date range on the user activity page
> Note: This task is reserved for Google Code-in students. Please do not claim this task. 

Steps to Reproduce: 
* Go to https://tools.wmflabs.org/wikicontrib/
* Provide user information (Fullname, Phabricator and Gerrit usernames)
* You will be redirected to a user activity page that will show "undefined" value for end date. The correct range for the current month should be "January 2019" - "December 2019" (see screenshot below)

Screen Shot 2019-12-12 at 10 42 26 AM

Hint: This would likely require minor code changes in the `frontend/WikiContrib-Frontend/src/result.js` file.

### PR DESCRIPTION
**Pull request by minhducsun2002**
Resolve #98.

### CODE REVIEW

**Comment by srish** [comment]
@minhducsun2002 Thanks a lot for your work on this! I am testing your change locally.. it mostly works fine for the month but the year is not showing correctly for the current time range. It is showing as "January 2017-December 2018", but it should be "January 2019-December 2019". Also, one thing that I noticed that that even with filters, specifically for the December month and time range set as 1 year, the date range displayed is +1 year.  For example, for `December 2019` it is: `January 2019-December 2020`. Perhaps, we need some more investigation on this :)

**Comment by minhducsun2002** [comment]
This should address the issue you mentioned.

**Comment by srish** [comment]
@minhducsun2002 Thank you! We will review your PR shortly..

**Comment by srish** [comment]
Thank you @minhducsun2002 for your PR! Sorry, it took us a long time to merge it.

**Pull request closed without merging**
