### PR TITLE
Automatically show information for first time uploading

### LINKED ISSUE #70: Show popup about the csv format on clicking the "bulk upload"
> Note: This task is reserved for Google Code-in students. Please do not claim this task.

Most of the users get confused because they do not directly see any format in which the CSV file need to be uploaded (of course it is there in the **info** button). But that is not a great idea because no one thinks that the format is specified over there. So, there can be a quick fix by making a popup on the info button specifying "View the CSV format here" for 5 to 6 seconds on clicking the bulk upload button.

This improves the user experience and helps the users.

### PR DESCRIPTION
**Pull request by minhducsun2002**
Resolve #70.

### CODE REVIEW

**Comment by rammanoj** [comment]
Hey, @minhducsun2002 thanks for the patch, the change looks good to me. I will merge it soon...

**Comment by minhducsun2002** [comment]
Tested yet?

**Comment by rammanoj** [comment]
Sorry for the delay... I have an exam today, so just got some time for testing :) these are the changes I suggest:

1. I haven't asked you to show the popup button :) but to be clear I have asked you to show a tooltip near the info button with the content "View the CSV format here" for around 10 secs (may be).

2. It's better to display the tooltip on the top.

**Bug in current implementation:**
 The below code is incorrect because the code works fine whenever the user clicks **bulk add** option immediately without performing any other events. But for suppose the user enters something in the username's and clear them and then click on **Bulk add**, then nothing will be displayed.

```js
  componentDidUpdate() {
    if (!this.state.bulkShown)
      setTimeout(() => this.setState({ bulkShown: true }), 5000);
  }
```

``ComponentDidUpdate()`` gets triggered whenever the state changes. So, if any of the event changes the state the ``this.state.bulkShown`` will be set to True.

This is not the intended approach. 

Thanks for the patch and waiting patiently for the review. The above two are the changes that need to be done :)

**Comment by minhducsun2002** [comment]
Hope this time there is no error. 

By the way, the commit history seems to be a little unclean. Should I squash and `push --force`?

**Comment by rammanoj** [comment]
Cool, it looks good now :)

I have a suggestion:
1. when the tooltip is opened, if I just perform some random click (on somewhere in the document), the csv file format image popup is being shown..

Can you please prevent this?

**Comment by minhducsun2002** [comment]
This should check if the clicked element is the trigger.

**Comment by rammanoj** [comment]
The change looks good to me :) Can you please squash all the commits. I will merge it as soon as you do it :)

**Comment by minhducsun2002** [comment]
Squashed all commits. This should be enough :D.

**Comment by rammanoj** [comment]
Thanks @minhducsun2002 for your contributions....

**Pull request merged**
