### PR TITLE
edit the commit_status for issue 60

### PR DESCRIPTION
**Pull request by jencwong**
Edit the commit_status in the backend to only include meaningful contributions, for Gerrit to include "merged" and for Phabricator to include "resolved" and "open" (ignoring "invalid," "declined" and "stalled")

### CODE REVIEW

**Comment by rammanoj** [comment]
@jencwong thanks for the contribution. It looks good to me. But I need a time of 3 to 4 days as I need to check if the app is working good with the current change. It had been some time since I looked into the code. So, give me 3 days. I will test it locally and respond appropriately.

**Comment by srish** [comment]
@rammanoj I tested this PR, and the contributions I see as a result of the changes made look good to me. The only thing that I am not sure about is whether we should keep `g-open` on the list. Not sure what it is about either. If it is related to Gerrit, then we don't need it. What say?

**Comment by jencwong** [comment]
> @rammanoj I tested this PR, and the contributions I see as a result of the changes made look good to me. The only thing that I am not sure about is whether we should keep `g-open` on the list. Not sure what it is about either. If it is related to Gerrit, then we don't need it. What say?

@srish I was also unsure of 'g-open'.  I saw that the status was deleted completely in the front-end but I found several references to 'g-open' in the backend (see screenshot) attached.   Let me know if 'g-open' should be deleted from settings.py (or completely from the backend).  I am happy to fix my codes. 

Screen Shot 2020-04-04 at 9 10 38 PM

**Comment by rammanoj** [comment]
I have tested it locally and it is working fine.

**Comment by rammanoj** [comment]
@srish, @jencwong While developing the tool. I got a issue regarding these status. There is open tag in both phabricator and gerrit. It indicates the bugs or patches that are open and assigned to particular developer. To differentiate them, I used `g-open` as open patches in gerrit and `p-open` as open patches in phabricator. @srish I am not completely sure if they need to be removed or not. Can you please specify it ?

**Comment by rammanoj** [comment]
I guess it is good to be merged once the the corresponding change about `g-open` is made :)

**Comment by jencwong** [comment]
> @srish, @jencwong While developing the tool. I got a issue regarding these status. There is open tag in both phabricator and gerrit. It indicates the bugs or patches that are open and assigned to particular developer. To differentiate them, I used `g-open` as open patches in gerrit and `p-open` as open patches in phabricator. @srish I am not completely sure if they need to be removed or not. Can you please specify it ?

@rammanoj thank you for the explanation! @srish let me know if you want the `g-open` status removed?

**Comment by srish** [comment]
@rammanoj So, for Gerrit, as per this task requirement, we track only those contributions that are `merged` and not the open ones. That probably means we should remove the use of `g-open.` Could you confirm if @jencwong should proceed with these changes?

**Comment by rammanoj** [comment]
Yep @srish he need to remove it. @jencwong please remove 'g-open' as per the above comment of @srish

**Comment by jencwong** [comment]
> Yep @srish they need to remove it. @jencwong please remove 'g-open' as per the above comment of @srish

@srish and @rammanoj  I removed the 'g-open' from the commit_status as discussed.

**Comment by srish** [comment]
@jencwong You will have to remove the use of `g-open` from other files as well. @rammanoj right?

**Comment by jencwong** [comment]
> @jencwong You will have to remove the use of `g-open` from other files as well. @rammanoj right?

@srish Agreed and removed `g-open` from other files.

**Comment by jencwong** [comment]
>I am going over and the formatting changes are not intentional.  I am not sure if I use an extension in my VS Code editor that caused the format changes, because I saw changes in the spaces/indentations on lines that I did not even touch.

**Comment by jencwong** [comment]
@srish so it is definitely an auto-formatting by an extension in my VS Code that caused the changes because I reverted to the old format and when I saved the file, it automatically caused the formatting changes again.  I have to investigate which extension is causing this.

**Comment by srish** [comment]
Thanks a lot @jencwong for your first contribution to this project :)

**Pull request merged**
