### PR TITLE
Replaced Contraband with WikiContrib name.

### PR DESCRIPTION
**Pull request by n3rsti**
I changed that in most of the files and changed directory names as well. I didn't change that only in 3 files:
Intro.html, Intro.rst - because there is pharagraph saying about old name of tool
api.js - because it's API url and it doesn't work without that.

I also found typo when reading readme.md and i created [Pull Request](https://github.com/wikimedia/WikiContrib/pull/91) with change (it's other PR, because I've seen typo before I started doing that task)

I tested it locally, both frontend and backend and it seems to work fine.

### CODE REVIEW

**Comment by rammanoj** [comment]
Hey Thanks for the PR. I need some time to review it. A lot of files are changed, so most of the functionalities are to be tested. I will test it and get back to you soon..

**Comment by n3rsti** [comment]
I know it's up to 36hrs to review, but is it working? :D

**Comment by rammanoj** [comment]
I don't think this will work, some changes need to be done.. :) I will list all the changes soon.

**Comment by n3rsti** [comment]
Ok, thanks. I thought this would work, at least it seemed to.

**Comment by srish** [comment]
@n3rsti Thanks a tonne for working on this big change! I've tested it locally, and everything works as intended. I have a few requests for minor changes:
* In `.env.example` file, keep the `BASE_URL_REMOTE` as it is `http://tools.wmflabs.org/contraband/` because our backend is hosted there currently :) 
* In `Intro.rst.txt` file, change the line "The tool was called WikiContrib..." line to "The tool was called Contraband..."
* Try to explicitly remove the folder `Contraband` in the code by `git rm -rf Contraband`. With your pull requests, I do get a new folder `WikiContrib` with correct files, but the previous one `Contraband` remains unchanged. I am not sure if it got correctly removed from the remote git repository. 

Other than that, I think your changes are ready to be merged :) 

@Rammanoj something for us to keep in mind that when we merge these changes, we move `.env` file to the appropriate location.

**Comment by n3rsti** [comment]
I changed WikiContrib to contraband, as you mentioned, but it looks like I deleted Contraband folder in git. I can't to git rm -rf in main directory, backend, frontend, because git can't find any file / folder with that name. Also in my github repo i don't have Contraband folder. Maybe in pull request changes it isn't renamed because it compares to wikimedia repository.

**Comment by rammanoj** [comment]
@n3rsti changes to be made:

1. Please don not update: ``docs/_build/html/Installation.html``. It has to be automatically generated.
2. Static URL should be ``wikicontrib`` not ``WikiContrib``
3. Please do not push db.sqite3 file.
4. Please do not push any files inside the directory named ``__pycache__``
5. In ``query/views.py``, the lines: ``response['location'] = '/contraband/result/'`` should not be replaced.
6. Please do not update ``docs/_build/html/searchindex.js``, it has to be automatically generated.

Thanks for your patience and work. You have done a great work :) Please do the above changes. Let me know if you have any more questions in it.

Once you have done the changes, I will test them locally once :)

**Comment by n3rsti** [comment]
I updated everything from your list, but I can't solve merge conflict. Even when that `Install.md` file was same as it from wikimedia repo, It still had conflict. I changed Contraband folder to WikiContrib, but `Install.md` is basically in the same place, but in different named folder.

**Comment by rammanoj** [comment]
I am even facing the similar issue.. I can neither merge the patch nor resolve the conflicts!! I will identify the error and get back to you. @srish if you find anything please notify us.

**Comment by n3rsti** [comment]
Oh, sorry. I thought that I have already done that.

**Comment by srish** [comment]
Thanks a lot @n3rsti for your code contributions :) I saw @rammanoj's quite when I had already merged your changes, it looks there are still a couple things remaining as per @rammanoj's comment. Would it be possible for you to send a new PR with those two changes? Thanks!

**Comment by n3rsti** [comment]
[Created PR](https://github.com/wikimedia/WikiContrib/pull/96)

**Pull request merged**
